# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-17 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Başlık')),
                ('Question_Content', models.TextField(verbose_name='Soru İçeriği')),
                ('publishing_date', models.DateTimeField(verbose_name='Yayımlanma Tarihi')),
            ],
        ),
    ]
