# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-23 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publishing_date', 'id']},
        ),
    ]
